using System.Text;

namespace Credfeto.Exceptions.SourceGenerator;

/// <summary>
///     Builds the source code for a generated exception class.
/// </summary>
internal static class ExceptionCodeBuilder
{
    /// <summary>
    ///     Generates the C# source code for an exception class with standard constructors.
    /// </summary>
    /// <param name="info">The exception class information.</param>
    /// <returns>The generated C# source code.</returns>
    public static string Build(ExceptionInfo info)
    {
        StringBuilder sb = new();

        AppendHeader(sb);
        AppendNamespace(sb, info.Namespace);
        AppendClassDeclaration(sb, info);
        sb.AppendLine("{");
        AppendDefaultConstructor(sb, info);
        sb.AppendLine();
        AppendMessageConstructor(sb, info.ClassName);
        sb.AppendLine();
        AppendMessageAndInnerExceptionConstructor(sb, info.ClassName);
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
    }

    private static void AppendNamespace(StringBuilder sb, string? namespaceName)
    {
        if (namespaceName is not null)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }
    }

    private static void AppendClassDeclaration(StringBuilder sb, ExceptionInfo info)
    {
        string sealedModifier = info.IsSealed
            ? " sealed"
            : string.Empty;

        sb.AppendLine($"{info.AccessModifier}{sealedModifier} partial class {info.ClassName} : Exception");
    }

    private static void AppendDefaultConstructor(StringBuilder sb, ExceptionInfo info)
    {
        if (info.Description is not null)
        {
            string escapedDescription = EscapeString(info.Description);
            sb.AppendLine($"    public {info.ClassName}()");
            sb.AppendLine($"        : this(\"{escapedDescription}\")");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    public {info.ClassName}() {{ }}");
        }
    }

    private static void AppendMessageConstructor(StringBuilder sb, string className)
    {
        sb.AppendLine($"    public {className}(string? message)");
        sb.AppendLine("        : base(message) { }");
    }

    private static void AppendMessageAndInnerExceptionConstructor(StringBuilder sb, string className)
    {
        sb.AppendLine($"    public {className}(string? message, Exception? innerException)");
        sb.AppendLine("        : base(message: message, innerException: innerException) { }");
    }

    private static string EscapeString(string value)
    {
        return value.Replace(@"\", @"\\")
                    .Replace("\"", "\\\"")
                    .Replace("\n", @"\n")
                    .Replace("\r", @"\r")
                    .Replace("\t", @"\t");
    }
}
