using System.Text;

namespace Credfeto.Exceptions.SourceGenerator;

/// <summary>
///     Builds the source code for a generated exception class.
/// </summary>
internal static class ExceptionCodeBuilder
{
    /// <summary>
    ///     Generates the C# source code for an exception class with standard constructors.
    /// </summary>
    /// <param name="info">The exception class information.</param>
    /// <returns>The generated C# source code.</returns>
    public static string Build(in ExceptionInfo info)
    {
        StringBuilder sb = new();

        AppendHeader(sb);
        AppendNamespace(sb, info.Namespace);
        AppendClassDeclaration(sb, info);
        sb.AppendLine("{");
        AppendDefaultConstructor(sb, info);
        sb.AppendLine();
        AppendMessageConstructor(sb, info.ClassName);
        sb.AppendLine();
        AppendMessageAndInnerExceptionConstructor(sb, info.ClassName);
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
    }

    private static void AppendNamespace(StringBuilder sb, string? namespaceName)
    {
        if (namespaceName is not null)
        {
            sb.Append("namespace ").Append(namespaceName).AppendLine(";");
            sb.AppendLine();
        }
    }

    private static void AppendClassDeclaration(StringBuilder sb, in ExceptionInfo info)
    {
        string sealedModifier = info.IsSealed ? " sealed" : string.Empty;

        sb.Append(info.AccessModifier)
            .Append(sealedModifier)
            .Append(" partial class ")
            .Append(info.ClassName)
            .AppendLine(" : Exception");
    }

    private static void AppendDefaultConstructor(StringBuilder sb, in ExceptionInfo info)
    {
        if (info.Description is not null)
        {
            string escapedDescription = EscapeString(info.Description);
            sb.Append("    public ").Append(info.ClassName).AppendLine("()");
            sb.Append("        : this(\"").Append(escapedDescription).AppendLine("\")");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
        }
        else
        {
            sb.Append("    public ").Append(info.ClassName).AppendLine("() { }");
        }
    }

    private static void AppendMessageConstructor(StringBuilder sb, string className)
    {
        sb.Append("    public ").Append(className).AppendLine("(string? message)");
        sb.AppendLine("        : base(message) { }");
    }

    private static void AppendMessageAndInnerExceptionConstructor(StringBuilder sb, string className)
    {
        sb.Append("    public ").Append(className).AppendLine("(string? message, Exception? innerException)");
        sb.AppendLine("        : base(message: message, innerException: innerException) { }");
    }

    private static string EscapeString(string value)
    {
        return value
            .Replace(@"\", @"\\")
            .Replace("\"", "\\\"")
            .Replace("\n", @"\n")
            .Replace("\r", @"\r")
            .Replace("\t", @"\t");
    }
}
