using System.Text;

namespace Credfeto.Exceptions.SourceGenerator;

/// <summary>
///     Builds the source code for a generated exception class.
/// </summary>
internal static class ExceptionCodeBuilder
{
    /// <summary>
    ///     Generates the C# source code for an exception class with standard constructors.
    /// </summary>
    /// <param name="info">The exception class information.</param>
    /// <returns>The generated C# source code.</returns>
    public static string Build(in ExceptionInfo info)
    {
        return new StringBuilder()
            .AppendHeader()
            .AppendNamespace(info.Namespace)
            .AppendGeneratedCode()
            .AppendClassDeclaration(info)
            .AppendLine("{")
            .AppendDefaultConstructor(info)
            .AppendLine()
            .AppendMessageConstructor(info)
            .AppendLine()
            .AppendMessageAndInnerExceptionConstructor(info)
            .AppendLine("}")
            .ToString();
    }

    private static StringBuilder AppendHeader(this StringBuilder sb)
    {

        return sb.AppendLine("// <auto-generated/>")
                 .AppendLine("#nullable enable")
                 .AppendLine()
            .AppendLine("using System;")
            .AppendLine("using System.CodeDom.Compiler;")
            .AppendLine();
    }

    private static StringBuilder AppendNamespace(this StringBuilder sb, string? namespaceName)
    {
        if (namespaceName is not null)
        {
            return sb.Append("namespace ").Append(namespaceName).AppendLine(";").AppendLine();
        }

        return sb;
    }

    private static StringBuilder AppendGeneratedCode(this StringBuilder sb)
    {
        return sb.Append("[GeneratedCode(\"Credfeto.Exceptions.CodeGenerator\", \"0.0.1.0\")]");
    }

    private static StringBuilder AppendClassDeclaration(this StringBuilder sb, in ExceptionInfo info)
    {
        string abstractModifier = info.IsAbstract ? " abstract" : string.Empty;
        string sealedModifier = info.IsSealed ? " sealed" : string.Empty;

        return sb.Append(info.AccessModifier)
            .Append(abstractModifier)
            .Append(sealedModifier)
            .Append(" partial class ")
            .Append(info.ClassName)
            .AppendLine(" : Exception");
    }

    private static StringBuilder AppendDefaultConstructor(this StringBuilder sb, in ExceptionInfo info)
    {
        string access = ConstructorAccess(info);

        if (info.Description is not null)
        {
            string escapedDescription = EscapeString(info.Description);

            return sb.Append("    ")
                .Append(access)
                .Append(' ')
                .Append(info.ClassName)
                .AppendLine("()")
                .Append("        : this(\"")
                .Append(escapedDescription)
                .AppendLine("\")")
                .AppendLine("    {")
                .AppendLine("    }");
        }

        return sb.Append("    ").Append(access).Append(' ').Append(info.ClassName).AppendLine("() { }");
    }

    private static StringBuilder AppendMessageConstructor(this StringBuilder sb, in ExceptionInfo info)
    {
        return sb.Append("    ")
            .Append(ConstructorAccess(info))
            .Append(' ')
            .Append(info.ClassName)
            .AppendLine("(string? message)")
            .AppendLine("        : base(message) { }");
    }

    private static StringBuilder AppendMessageAndInnerExceptionConstructor(this StringBuilder sb, in ExceptionInfo info)
    {
        return sb.Append("    ")
            .Append(ConstructorAccess(info))
            .Append(' ')
            .Append(info.ClassName)
            .AppendLine("(string? message, Exception? innerException)")
            .AppendLine("        : base(message: message, innerException: innerException) { }");
    }

    private static string ConstructorAccess(in ExceptionInfo info)
    {
        return info.IsAbstract ? "protected" : "public";
    }

    private static string EscapeString(string value)
    {
        return value
            .Replace(oldValue: @"\", newValue: @"\\")
            .Replace(oldValue: "\"", newValue: "\\\"")
            .Replace(oldValue: "\n", newValue: @"\n")
            .Replace(oldValue: "\r", newValue: @"\r")
            .Replace(oldValue: "\t", newValue: @"\t");
    }
}
